### ISSUE TITLE
Does not output any changelogs

### ISSUE THREAD

**Issue by williamengbjerg** [OwenMelbz/change-log-now#2]
@OwenMelbz I've tried to use your script. It looks great. But the command output nothing on changelog.md (Using NPM  v7.4.3)

![image](https://user-images.githubusercontent.com/54719/106038305-12d3b980-60d8-11eb-9f8f-d44c9b898c0f.png)

When I ran cln --init first time I got an error (created the changelog.config.js manually. 
![image](https://user-images.githubusercontent.com/54719/106038395-33037880-60d8-11eb-8aa0-a9501773f131.png)

**Comment by OwenMelbz** [comment]
Hi,

What version of nodejs are you using?

And what do your commit messages look like?

There needs to be an identifiable pattern in them which allows it to categorise them, e.g. if you look in the config you will see 

```js
triggers: [
    "🐛 Bug",
    "🚀 Feature",
    "💥 Change",
  ],
```

So if your commit message starts with any of those it will add them to the log, if there's no pattern it cannot pull anything in.

**Comment by williamengbjerg** [comment]
Oh doh. I get it. The triggers was ofc not set correct. Thanks a lot. Super useful 👍🏼
